title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!

# set theme for local
theme: "just-the-docs"

# set theme for github
# remote_theme: pmarsceill/just-the-docs

# replace with your url
url: https://Han-Cao.github.io/doc-template

aux_links:
  Edit on Github: https://github.com/Han-Cao/doc-test
  
# Color scheme 
color_scheme: custom