title: Just the Docs Template
description: A modified template for a Jeykll site using the Just the Docs theme!

theme: just-the-docs

# replace with your url
url: https://Han-Cao.github.io
baseurl: /doc-template

aux_links:
  View on Github: https://github.com/Han-Cao/doc-template
  
# Color scheme 
color_scheme: custom


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e, %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
